export const data = {
    products:[
    {
        _id:1,
        name:'Nike SLim Shirt',
        category:'Shirts',
        image:'/images/product1.jpg',
        price:120,
        rating:4.5,
        numRevies:10,
        description:'high quality product',
    },
    {
        _id:2,
        name:'Nike SLim Shirt',
        category:'Shirts',
        image:'/images/product1.jpg',
        price:120,
        rating:4.5,
        numRevies:10,
        description:'high quality product',
    },
    {
        _id:1,
        name:'Nike SLim Shirt',
        category:'Shirts',
        image:'/images/product1.jpg',
        price:120,
        rating:4.5,
        numRevies:10,
        description:'high quality product',
    },
    {
        _id:3,
        name:'Nike SLim Shirt',
        category:'Shirts',
        image:'/images/product1.jpg',
        price:120,
        rating:4.5,
        numRevies:10,
        description:'high quality product',
    },
    {
        _id:4,
        name:'Nike SLim Shirt',
        category:'Shirts',
        image:'/images/product1.jpg',
        price:120,
        rating:4.5,
        numRevies:10,
        description:'high quality product',
    },
    {
        _id:5,
        name:'Nike SLim Shirt',
        category:'Shirts',
        image:'/images/product1.jpg',
        price:120,
        rating:4.5,
        numRevies:10,
        description:'high quality product',
    },
    {
        _id:6,
        name:'Nike SLim Shirt',
        category:'Shirts',
        image:'/images/product1.jpg',
        price:120,
        rating:4.5,
        numRevies:10,
        description:'high quality product',
    },
]
}
